# Lists of checks to explicitly enable or disable. If a prefix is given (e.g.
# "namespace"), all checks matching that prefix will be matched.
[checks]
enabled = ["enum.explicit", "field.id.zero", "names.casing", "map.key.type"]
disabled = []


# Configuration values for specific checks:
[checks.names]
reserved = [
    "template",
]
 
 