# Lists of checks to explicitly enable or disable. If a prefix is given (e.g.
# "namespace"), all checks matching that prefix will be matched.
[checks]
enabled = ["enum", "field.id.zero", "names.casing"]
disabled = []


# Configuration values for specific checks:
[checks.names]
reserved = [
    "template",
]
 
 